VideoComposer: Compositional Video Synthesis with Motion Controllability
modelscope/modelscope pull request #431
Opened 2023-07-31 07:28 UTC by XDUWQ

For more information, please refer to：https://videocomposer.github.io/

2023-08-08 08:28 UTC, wenmengzhou requested changes

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/models/multi_modal/videocomposer/utils/logging.py
> +
remove,  use modelscope logging

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +class VideoComposer(Model):
继承TorchModel

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +            image_key = self.cfg.image_path
为什么是从self.cfg中获取image_path   sketch_path？  应该从forward input中获取

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +            frame = Image.open(open(image_key, mode='rb')).convert('RGB')
use  modelscope/preprocessors/image.py load_image/LoadImage

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +                    - A string, the *model id* of a pretrained model hosted inside a model repo on huggingface.co
remove huggingface.co

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +                visualize_with_model_kwargs(
看起来没有必要可视化？

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    def __init__(self, model: str, **kwargs):
参考 https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/cv/card_detection_pipeline.py#L18  补充pipeline注释

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +            print('The video path does not exist or no video dir provided!')
use modelscope logger

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    def _get_video_traindata(self, video_key, feature_framerate, total_frames,
名字较为奇怪，看起来是在计算motion vector？

2023-08-08 08:28 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +        if visual_mv:
remove可视化

2023-08-08 08:28 UTC, wenmengzhou commented on tests/pipelines/test_videocomposer.py
> +    @unittest.skipUnless(test_level() >= 1, 'skip test in current test level')
why skip test in CI？

2023-08-09 03:29 UTC, Steven-SWZhang commented on configs/multi_modal/exp06_text_depths_vs_style.yaml
> +TASK_TYPE: SINGLE_TASK
可以的。

2023-08-09 03:32 UTC, Steven-SWZhang commented on modelscope/models/multi_modal/videocomposer/ops/degration.py
> +import math
功能一致，可以复用。

2023-08-09 03:58 UTC, XDUWQ commented on tests/pipelines/test_videocomposer.py
> +    @unittest.skipUnless(test_level() >= 1, 'skip test in current test level')
依赖的环境安装包比较严格，modelscope现在的CI环境跑不通

2023-08-10 03:13 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +class VideoComposer(Model):
> 继承TorchModel

done

2023-08-10 03:15 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +        if visual_mv:
> remove可视化
这是保存结果的逻辑，我认为还是需要保留的

2023-08-10 03:18 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    def _get_video_traindata(self, video_key, feature_framerate, total_frames,
> 名字较为奇怪，看起来是在计算motion vector？

已改名

2023-08-10 03:23 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/ops/degration.py
> +import math
已删除

2023-08-10 03:25 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +                    - A string, the *model id* of a pretrained model hosted inside a model repo on huggingface.co
done

2023-08-10 03:26 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +                visualize_with_model_kwargs(
这里的可视化是保存结果，我改一个名字吧

2023-08-10 03:30 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/random_mask.py
> +# Copyright (c) Alibaba, Inc. and its affiliates.
已删除

2023-08-10 03:36 UTC, XDUWQ commented on configs/multi_modal/exp06_text_depths_vs_style.yaml
> +TASK_TYPE: SINGLE_TASK
done

2023-08-10 03:53 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    def __init__(self, model: str, **kwargs):
done

2023-08-10 03:55 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/utils/logging.py
> +
done

2023-08-10 03:56 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +            print('The video path does not exist or no video dir provided!')
done

2023-08-10 06:39 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +            frame = Image.open(open(image_key, mode='rb')).convert('RGB')
done

2023-08-10 06:43 UTC, XDUWQ commented on modelscope/models/multi_modal/videocomposer/videocomposer_model.py
> +            image_key = self.cfg.image_path
done

2023-08-10 11:03 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    >>> ds = MsDataset.load('buptwq/videocomposer-depths-style', split='train')
这个示例有些奇怪，使用单个video url作为输入， 另外没有self.text

2023-08-10 11:08 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +        if visual_mv:
这里是保存了mv的可视化结果，并不影响最终返回视频结果把

2023-08-10 11:09 UTC, wenmengzhou commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    def postprocess(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
参考text_to_video的pipeline，如果指定output_video，返回生成后的video_Path

2023-08-10 11:31 UTC, wenmengzhou commented on tests/pipelines/test_videocomposer.py
> +    @unittest.skipUnless(test_level() >= 1, 'skip test in current test level')
需要哪些依赖？ 在模型库中写上requirements.txt   动态安装？

2023-08-11 01:38 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    >>> ds = MsDataset.load('buptwq/videocomposer-depths-style', split='train')
已更正

2023-08-11 01:47 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +        if visual_mv:
好的，已更正

2023-08-11 02:22 UTC, XDUWQ commented on modelscope/pipelines/multi_modal/videocomposer_pipeline.py
> +    def postprocess(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
已改正

2023-08-11 02:35 UTC, XDUWQ commented
@wenmengzhou 
`distributed.py` 是原代码中不同文件夹下的不同文件，非重复；
`losses.py` 重复问题已改正
![image](https://github.com/modelscope/modelscope/assets/37444407/59637905-fa34-4452-a4fd-21c4f3142582)

2023-08-13 13:04 UTC, XDUWQ commented on tests/pipelines/test_videocomposer.py
> +    @unittest.skipUnless(test_level() >= 1, 'skip test in current test level')
motion-vector-extractor>=1.0.6
numpy>=1.24.2
scikit-video>=1.1.11
pynvml>=11.5.0
bitsandbytes==0.38.1

2023-08-13 13:17 UTC, XDUWQ commented on tests/pipelines/test_videocomposer.py
> +    @unittest.skipUnless(test_level() >= 1, 'skip test in current test level')
videocomposer和modelscope对numpy的版本要求有冲突，CI测试暂时无法跑通

2023-08-15 04:00 UTC, wenmengzhou approved these changes

2023-08-15 04:01 UTC, merged