add syncdreamer as a image-to-3d pipeline
modelscope/modelscope pull request #679
Opened 2023-12-14 03:31 UTC by hitsz-zuoqi

1、Syncdreamer is a image-to-3d method. It can generate 16 views based on a single image.
2、The added components have passed the unitest and ready for integration.
```

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
import numpy as np
from PIL import Image

image23D = pipeline(
            Tasks.image_to_3d,
            model='Damo_XR_Lab/Syncdreamer')

result = image23D('./basketball.png')
# print(result)

np_content = []
for idx,img in enumerate(result['MViews']):
    np_content.append(np.array(result['MViews'][idx]))

np_content = np.concatenate(np_content, axis=1)
Image.fromarray(np_content).save("./demo_output/concat.png")
    # result['MViews'][idx].save("./demo_output/test_{:04d}.png".format(idx))

```

2023-12-14 07:39 UTC, wenmengzhou requested changes
remove directory `demo_output`

2023-12-18 03:00 UTC, hitsz-zuoqi commented
> remove directory `demo_output`

ok, I will remove the demo_output

2023-12-18 03:10 UTC, hitsz-zuoqi commented
> remove directory `demo_output`

I have removed the `demo_output` as requested. I think a potential modification you may request is add specific dependency to the `cv.txt`. The dependency I installed after I `install -r requirements/framework.txt` includes:
```

pytorch_lightning
kornia
matplotlib
git+https://github.com/openai/CLIP.git
omegaconf
taming-transformers-rom1504 
rembg

```

I don't know if I should add these requirements? plz.

2023-12-18 08:50 UTC, hitsz-zuoqi commented
> > remove directory `demo_output`
> 
> I have removed the `demo_output` as requested. I think a potential modification you may request is add specific dependency to the `cv.txt`. The dependency I installed after I `install -r requirements/framework.txt` includes:
> 
> ```
> 
> pytorch_lightning
> kornia
> matplotlib
> git+https://github.com/openai/CLIP.git
> omegaconf
> taming-transformers-rom1504 
> rembg
> ```
> 
> I don't know if I should add these requirements? plz.

as your command, I have added these requirements as a requirements.txt in modelhub. Check it here:
https://modelscope.cn/models/Damo_XR_Lab/Syncdreamer/summary

2023-12-20 07:19 UTC, hitsz-zuoqi commented on modelscope/models/cv/image_to_3d/ldm/models/diffusion/sync_dreamer.py
> +class SyncMultiviewDiffusion(pl.LightningModule):
> give some introduction of model here , and the paper link if it has

Done. I hide the install of clip using "os.system()", too.(In pipeline)

```

import os
os.system("pip install git+https://github.com/openai/CLIP.git")

```

2023-12-20 07:51 UTC, hitsz-zuoqi commented on modelscope/models/cv/image_to_3d/ldm/models/diffusion/sync_dreamer.py
> +class SyncMultiviewDiffusion(pl.LightningModule):
> give some introduction of model here , and the paper link if it has

Done.

2023-12-20 13:31 UTC, wenmengzhou reviewed
LGTM

2023-12-21 14:12 UTC, wenmengzhou approved these changes

2023-12-21 14:12 UTC, merged