Feature/LoFTR_image_local_feature_matching
modelscope/modelscope pull request #687
Opened 2023-12-21 04:04 UTC by ethnhe

Add image local feature matching LoFTR pipeline and model.

2023-12-28 08:21 UTC, wenmengzhou commented
merge latest master and rerun the tests

2023-12-28 08:36 UTC, wenmengzhou requested changes
images in test/images  should be uploaded using git-lfs, please refer to

https://github.com/modelscope/modelscope/blob/master/docs/source/develop_cn.md#23-%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8

2023-12-28 08:37 UTC, wenmengzhou commented on modelscope/pipelines/cv/image_local_feature_matching_pipeline.py
> +    """ Image Local Feature Matching Pipeline.
add pipeline doc str, refer to https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/cv/card_detection_correction_pipeline.py#L34C1-L34C1

2023-12-28 09:31 UTC, ethnhe commented
Modified as mentioned.

2023-12-28 09:34 UTC, ethnhe commented
Modified as mentioned.

2024-01-17 13:31 UTC, wenmengzhou approved these changes

2024-01-17 13:51 UTC, merged